[platformio]
default_envs = qbyte
src_dir = code/main
data_dir = code/main/data

[env:qbyte]
platform = espressif32@3.5.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
board_build.partitions = partitions.csv
lib_deps =
    fastled/FastLED@3.5.0
    bblanchon/ArduinoJson@6.17.2
    https://github.com/gelraen/Arduino-PID-Library.git#2b23112815ed5e0adc2d64d06f9f4e909116315b
    file://libraries/Adafruit_ADS1X15.zip
    file://libraries/Adafruit_BusIO.zip
    file://libraries/Adafruit_TLA202x.zip
    file://libraries/Adafruit_Unified_Sensor.zip
    file://libraries/AsyncTCP-master.zip
    file://libraries/ESP32-TLA2024.zip
    file://libraries/ESP8266-Websocket-master.zip
    file://libraries/ESPAsyncWebServer-ReadmeImpr.zip
    file://libraries/TLC59108-main.zip
    file://libraries/esp32FOTA-master.zip
